### PR TITLE
Add configuration option tenant_id to make the client tenant aware

### PR DESCRIPTION
**Pull request by eriwin**
You can now set the tenant_id in the config to make the client tenant aware.

Example:
```
kreait_firebase:
  projects:
    myproject:
      tenant_id: 'test-fmo4p'
```

I also updated the README.md and added a unit test. It would be great if this is something you would like to add to the bundle. Let me know if I can do anything else for this pull request.

### CODE REVIEW

**Comment by jeromegamez** [comment]
Thank you, Erik 🌺! From my mobile phone this looks perfect, I'll have a finishing look and merge it as soon as I'm back at my computer 💪!

**Comment by eriwin** [comment]
Thank you for your quick reply. I do see the Travis-ci pipelines failing but it does not seem related to the changes I made?

**Comment by jeromegamez** [comment]
No, they are broken since forever, but that's not related to the code, of course, I just didn't manage to migrate them to GitHub Actions yet 🙈

**Comment by eriwin** [comment]
I understand. Good to know 😄

**Comment by jeromegamez** [comment]
Well, that's embarrassing... it was *me* who broke the tests a couple of weeks ago when I changed something in the underlying SDK, but 🤫🤫🤫. It will be broken in a couple of weeks when travis-ci.org shuts down, but it will not be because of the code at least 😅.

Long story short: merged with https://github.com/kreait/firebase-bundle/commit/588cc89a32fb2ddf70203efd82b52182819072fa and released with [release 2.4.0](https://github.com/kreait/firebase-bundle/releases/tag/2.4.0) 🚀 

Thanks again! 🌺

**Comment by eriwin** [comment]
Thank you!

**Comment by dgommers** [comment]
@jeromegamez We appreciate your quick response on this request. Thanks again.

**Pull request closed without merging**
