### PR TITLE
Add ability to override project id

### LINKED ISSUE #62: Overriding project id per configuration entry
### Describe the feature you would like to see

Hi,

we're starting to use your bundle (and great lib) for push notifications. In our situation our backend service lives in project A and the apps live in project B. We run within GCP so our workloads have a service account for project A available. This service account has been given the roles for FCM in project B. It can send notifications when testing locally (with SA key file for project A but changing the project to B manually in the file). However, when we deploy the service account that is automatically provided will resolve to project A, not B. Meaning it cannot send messages. Ideally, it would be possible to simply override with an extra config entry field:

```yaml
kreait_firebase:
    projects:
        some-project-name:
            project_id: project-b
```

In the base library this seems possible by calling `::withProjectId(...)`, so right now I am leaning to use the library directly and write a new factory. But of course, being able to do this with the bundle is more appropriate.

Is there something I am missing or is it indeed a usecase that is not supported yet? If it is not supported would a PR be welcome?

### PR DESCRIPTION
**Pull request by rogierknoester**
# Description
Sometimes credentials are from a different GCP project than the service being used (e.g. a workload in project A needs to access apps in project B). These changes allow overriding the project id, as it is usually part of the service account's credentials already.

Fixes #62 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jeromegamez — APPROVED** [review]
Thank you very much, this is a perfect PR! 🫶🏻

**Comment by jeromegamez** [comment]
I will release it tomorrow when I'm back at my desk!

**Comment by jeromegamez** [comment]
Done! https://github.com/kreait/firebase-bundle/releases/tag/5.4.0

**Comment by rogierknoester** [comment]
Thanks for the quick responses!

**Pull request merged**
